const THEMES = [
  {
    name: "Under the Sea",
    backgroundColor: "#FBE0C4",
    boardColor: "#8AB6D6",
    buttonColor: "#2978B5",
    buttonColorHover: "#0061A8",
    buttonColorPressed: "#0061A8",
    textColor: "#000000",
    textStyle: "light",
    marker1: "&#x1F980;",
    marker2: "&#x1F420;",
  },
  {
    name: "Classic",
    backgroundColor: "#ffffff",
    boardColor: "#ffffff",
    buttonColor: "#2ecc71",
    buttonColorHover: "#27ae60",
    buttonColorPressed: "#269455",
    textColor: "#000000",
    textStyle: "dark",
    marker1: '<span style="color: white">O</span>',
    marker2: '<span style="color: white">X</span>',
  },
];
